### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by AlexIs72** [twostairs/paperwork#237]
Hi!
I have a problem with Paperwork installation. 

/opt/www/notes/paperwork/frontend# export PATH=/opt/nodejs/bin:$PATH;/opt/nodejs/bin/gulp 
[12:11:04] Using gulpfile /opt/www/notes/paperwork/frontend/gulpfile.js
[12:11:04] Starting 'compileLessBootstrapTheme'...
[12:11:04] Finished 'compileLessBootstrapTheme' after 55 ms
[12:11:04] Starting 'compileLessPaperworkThemeV1'...
[12:11:04] Finished 'compileLessPaperworkThemeV1' after 24 ms
[12:11:04] Starting 'compileLessFreqselector'...
[12:11:05] Finished 'compileLessFreqselector' after 8.38 ms
[12:11:05] Starting 'compileLessTypeahead'...
[12:11:05] Finished 'compileLessTypeahead' after 7.33 ms
[12:11:05] Starting 'less'...
[12:11:05] Finished 'less' after 24 μs
[12:11:05] Starting 'compileJsBootstrap'...
[12:11:05] Finished 'compileJsBootstrap' after 28 ms
[12:11:05] Starting 'compileJsPaperwork'...
[12:11:05] Finished 'compileJsPaperwork' after 8.67 ms
[12:11:05] Starting 'compileJsAngular'...
[12:11:05] Finished 'compileJsAngular' after 27 ms
[12:11:05] Starting 'compileJsJquery'...
[12:11:05] Finished 'compileJsJquery' after 35 ms
[12:11:05] Starting 'compileJsTagsinput'...
[12:11:05] Finished 'compileJsTagsinput' after 12 ms
[12:11:05] Starting 'compileJsLibraries'...
[12:11:05] Finished 'compileJsLibraries' after 10 ms
[12:11:05] Starting 'compileJsLtIe9Compat'...
[12:11:05] Finished 'compileJsLtIe9Compat' after 7.09 ms
[12:11:05] Starting 'compileJsLtIe11Compat'...
[12:11:05] Finished 'compileJsLtIe11Compat' after 13 ms
[12:11:05] Starting 'js'...
[12:11:05] Finished 'js' after 21 μs
[12:11:05] Starting 'default'...
[12:11:05] Finished 'default' after 21 μs
/opt/www/notes/paperwork/frontend/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (/opt/www/notes/paperwork/frontend/node_modules/gulp-less/index.js:68:8)
    at DestroyableTransform.Transform._read (/opt/www/notes/paperwork/frontend/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/opt/www/notes/paperwork/frontend/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/opt/www/notes/paperwork/frontend/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/opt/www/notes/paperwork/frontend/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/opt/www/notes/paperwork/frontend/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/opt/www/notes/paperwork/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/opt/www/notes/paperwork/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/opt/www/notes/paperwork/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)

I using latest version of Paperwork, node.js and gulp.

**Comment by devilx** [comment]
Oh, that's weird. I just tested building master and everything works. What branch are you trying right now?

**Comment by AlexIs72** [comment]
I clone latest brach. I did step-by-step on instruction

**Comment by AlexIs72** [comment]
Resloved.
It's version's incompatibility.
After install:

>npm install gulp-less@2.0.1
>npm install gulp-concat@2.4.2
>npm install gulp-rename@1.2.0
>npm install gulp-livereload@3.2.0
>npm install gulp-uglify@1.1.0

All ok:
 gulp
[18:07:12] Using gulpfile /opt/www/notes/paperwork/frontend/gulpfile.js
[18:07:12] Starting 'compileLessBootstrapTheme'...
[18:07:12] Finished 'compileLessBootstrapTheme' after 63 ms
[18:07:12] Starting 'compileLessPaperworkThemeV1'...
[18:07:12] Finished 'compileLessPaperworkThemeV1' after 23 ms
[18:07:12] Starting 'compileLessFreqselector'...
[18:07:12] Finished 'compileLessFreqselector' after 7.85 ms
[18:07:12] Starting 'compileLessTypeahead'...
[18:07:12] Finished 'compileLessTypeahead' after 9.21 ms
[18:07:12] Starting 'less'...
[18:07:12] Finished 'less' after 22 μs
[18:07:12] Starting 'compileJsBootstrap'...
[18:07:12] Finished 'compileJsBootstrap' after 31 ms
[18:07:12] Starting 'compileJsPaperwork'...
[18:07:12] Finished 'compileJsPaperwork' after 22 ms
[18:07:12] Starting 'compileJsAngular'...
[18:07:12] Finished 'compileJsAngular' after 34 ms
[18:07:12] Starting 'compileJsJquery'...
[18:07:12] Finished 'compileJsJquery' after 39 ms
[18:07:12] Starting 'compileJsTagsinput'...
[18:07:12] Finished 'compileJsTagsinput' after 14 ms
[18:07:12] Starting 'compileJsLibraries'...
[18:07:12] Finished 'compileJsLibraries' after 8.15 ms
[18:07:12] Starting 'compileJsLtIe9Compat'...
[18:07:12] Finished 'compileJsLtIe9Compat' after 7.16 ms
[18:07:12] Starting 'compileJsLtIe11Compat'...
[18:07:12] Finished 'compileJsLtIe11Compat' after 12 ms
[18:07:12] Starting 'js'...
[18:07:12] Finished 'js' after 23 μs
[18:07:12] Starting 'default'...
[18:07:12] Finished 'default' after 22 μs


Installtion procedure do not work with latest versions of node modules.
Will continue installation and testing.

**Comment by Baldrs** [comment]
What are the exact versions of npm and nodejs?

**Comment by AlexIs72** [comment]
/opt/nodejs/bin# ./npm -v
2.5.1

/opt/nodejs# cat ChangeLog | head -n 10
2015.02.06, Version 0.12.0 (Stable)

* npm: Upgrade to 2.5.1

* mdb_v8: update for v0.12 (Dave Pacheco)

**Comment by devilx** [comment]
Any news here?

**Comment by nixsiow** [comment]
Thanks for you pointing out the incompatible node module's version. Help me alot, cheers!

**Comment by Baldrs** [comment]
Seems to be abandoned, closing till it gets any attention.

**Comment by skeidel** [comment]
Had the same issue in Debian wheezy 7.8 with the very latest npm 2.7.4 just now. Pinning the packages listed by @AlexIs72 above worked though.
