### ISSUE TITLE
gulp does not work

### ISSUE THREAD

**Issue by unnikked** [twostairs/paperwork#293]
I'm finding trouble on running gulp, cloned the repository today 18 March 2015

```shell
pi@raspberrypi /var/www/paperwork/frontend $ sudo gulp
[15:56:35] Using gulpfile /var/www/paperwork/frontend/gulpfile.js
[15:56:35] Starting 'compileLessBootstrapTheme'...
[15:56:36] Finished 'compileLessBootstrapTheme' after 321 ms
[15:56:36] Starting 'compileLessPaperworkThemeV1'...
[15:56:36] Finished 'compileLessPaperworkThemeV1' after 140 ms
[15:56:36] Starting 'compileLessFreqselector'...
[15:56:36] Finished 'compileLessFreqselector' after 44 ms
[15:56:36] Starting 'compileLessTypeahead'...
[15:56:36] Finished 'compileLessTypeahead' after 30 ms
[15:56:36] Starting 'less'...
[15:56:36] Finished 'less' after 125 μs
[15:56:36] Starting 'compileJsBootstrap'...
[15:56:36] Finished 'compileJsBootstrap' after 169 ms
[15:56:36] Starting 'compileJsPaperwork'...
[15:56:36] Finished 'compileJsPaperwork' after 70 ms
[15:56:36] Starting 'compileJsAngular'...
[15:56:36] Finished 'compileJsAngular' after 91 ms
[15:56:36] Starting 'compileJsJquery'...
[15:56:36] Finished 'compileJsJquery' after 47 ms
[15:56:36] Starting 'compileJsTagsinput'...
[15:56:36] Finished 'compileJsTagsinput' after 47 ms
[15:56:36] Starting 'compileJsLibraries'...
[15:56:36] Finished 'compileJsLibraries' after 35 ms
[15:56:36] Starting 'compileJsLtIe9Compat'...
[15:56:36] Finished 'compileJsLtIe9Compat' after 33 ms
[15:56:36] Starting 'compileJsLtIe11Compat'...
[15:56:36] Finished 'compileJsLtIe11Compat' after 26 ms
[15:56:36] Starting 'js'...
[15:56:36] Finished 'js' after 122 μs
[15:56:36] Starting 'default'...
[15:56:36] Finished 'default' after 124 μs
/var/www/paperwork/frontend/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (/var/www/paperwork/frontend/node_modules/gulp-less/index.js:68:8)
    at DestroyableTransform.Transform._read (/var/www/paperwork/frontend/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/var/www/paperwork/frontend/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/var/www/paperwork/frontend/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/var/www/paperwork/frontend/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/var/www/paperwork/frontend/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/var/www/paperwork/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/var/www/paperwork/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/var/www/paperwork/frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
```

I'm using `nodejs v0.12.0` and `npm 2.7.1` on a raspberry pi that runs raspbian.

**Comment by unnikked** [comment]
sorry for double posting, the issue seems already been resolved in #237
