### ISSUE TITLE
Saving note with code snippet - error

### ISSUE THREAD

**Issue by doc-jay** [twostairs/paperwork#357]
Running the latest git code from paperwork

I am trying to save a note with a code snippet that is a MYSQL query.  It acts as it saves it, but after you go back to your note, it doesn't have any snippet at all.  I can enter plain text in it just fine.

When I do the code snippet, I choose 'SQL' but it doesn't matter which one I choose, they all act the same way.

Here is the laravel.log:

```
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content_preview' at row 1 (SQL: insert into `versions` (`title`, `content`, `content_preview`, `updated_at`, `created_at`) values (test note, <pre><code class="language-sql">select distinct(t2_f_instance.sop_cuid), count(*) as count
from files t0_f, filesystem t1_f_fileSystem, instance t2_f_instance
WHERE t0_f.file_status = 0 
AND t0_f.file_tsuid = '1.2.840.10008.1.2' 
AND t1_f_fileSystem.pk
in ('1', '2', '3')
AND t0_f.filesystem_fk=t1_f_fileSystem.pk
AND t0_f.instance_fk=t2_f_instance.pk
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.11.1'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.11'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.22'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.33'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.50'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.59'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.67'
AND t0_f.created_time &lt; now() - INTERVAL 1 day
group by t2_f_instance.sop_cuid</code></pre><p>new test</p>, select distinct(t2_f_instance.sop_cuid), count(*) as count
from files t0_f, filesystem t1_f_fileSystem, instance t2_f_instance
WHERE t0_f.file_status = 0 
AND t0_f.file_tsuid = '1.2.840.10008.1.2' 
AND t1_f_fileSystem.pk
in ('1', '2', '3')
AND t0_f.filesystem_fk=t1_f_fileSystem.pk
AND t0_f.instance_fk=t2_f_instance.pk
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.11.1'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.11'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.22'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.33'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.50'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.59'
and t2_f_instance.sop_cuid != '1.2.840.10008.5.1.4.1.1.88.67'
AND t0_f.created_time &lt; now() - INTERVAL 1 day
group by t2_f_instance.sop_cuidnew test, 2015-04-27 16:27:52, 2015-04-27 16:27:52))' in /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `ve...', Array, Object(Closure))
#1 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `ve...', Array, Object(Closure))
#2 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `ve...', Array)
#3 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `ve...', Array)
#4 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ve...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1550): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1456): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/paperwork/frontend/app/controllers/api/v1/ApiNotesController.php(265): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: ApiNotesController->update('0', '22')
#13 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('update', Array)
#15 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(ApiNotesController), Object(Illuminate\Routing\Route), 'update')
#16 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ApiNotesControl...', 'update')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('0', '22')
#18 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#19 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/paperwork/frontend/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#28 /var/www/html/paperwork/frontend/public/index.php(49): Illuminate\Foundation\Application->run()
#29 {main}
```

**Comment by Liongold** [comment]
I couldn't replicate this issue. Can you provide some sample note text and screenshots of the browser network console, please?

**Comment by Liongold** [comment]
I couldn't replicate this issue using Paperwork 
b169a1e8b46a257c9b8a9248e4ab4f9224cdcb37. If you re-encounter this issue, please reopen this issue with more details. Thanks for your feedback.
