### ISSUE TITLE
gulp default task fails

### ISSUE THREAD

**Issue by thgie** [twostairs/paperwork#398]
Everything worked so far. Trying to setup on windows 8. No errors on npm install.

```
C:\xampp\htdocs\paperwork\frontend>gulp

module.js:340
    throw err;
          ^
Error: Cannot find module './lib/_stream_transform.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\xampp\htdocs\paperwork\frontend\node_modules\gulp-livereload\node_modules\gulp-util\node_modules\through2\node_modules\readable-st
ream\transform.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by thgie** [comment]
I just ommit the livereload and jshint modules and it works.

**Comment by Baldrs** [comment]
Keep in mind that windows is not supported intentionally. It should work, but that is not guaranteed.

**Comment by thgie** [comment]
It works pretty fine. Also had to execute bower install. Missed that in the documentation. It works fine and awesome work. Thanks :)
