### ISSUE TITLE
Just updated - can't view contents of notebooks

### ISSUE THREAD

**Issue by doc-jay** [twostairs/paperwork#439]
CENTOS7
nginix
mysql

So I was having issues last week updating paperwork, so I backed up my original paperwork folder and did another 'git clone' of paperwork.  After the install I edited the 'database.php' file to point to my existing DB.  Then I installed composer, npm, gulp, & bower.

After that I ran 'php artisan paperwork:update' hoping that it would update my DB schema because I was experiencing issues otherwise.  

Everything went okay, but after I login to paperwork, I can see my notebooks, but cannot access them.

Here is a snippet from the laravel.log

````
[2015-06-29 15:52:22] production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'versions.user_id' in 'field list'' in /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php:299
Stack trace:
#0 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(299): PDO->prepare('select `version...')
#1 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select `version...', Array)
#2 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('select `version...', Array, Object(Closure))
#3 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\Database\Connection->run('select `version...', Array, Object(Closure))
#4 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1412): Illuminate\Database\Connection->select('select `version...', Array)
#5 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1397): Illuminate\Database\Query\Builder->runSelect()
#6 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1384): Illuminate\Database\Query\Builder->getFresh(Array)
#7 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(411): Illuminate\Database\Query\Builder->get(Array)
#8 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(151): Illuminate\Database\Eloquent\Builder->getModels(Array)
#9 [internal function]: Illuminate\Database\Eloquent\Builder->get()
#10 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(281): call_user_func_array(Array, Array)
#11 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(103): Illuminate\Database\Eloquent\Relations\Relation->__call('get', Array)
#12 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(103): Illuminate\Database\Eloquent\Relations\BelongsTo->get()
#13 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(476): Illuminate\Database\Eloquent\Relations\Relation->getEager()
#14 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(445): Illuminate\Database\Eloquent\Builder->loadRelation(Array, 'version', Object(Closure))
#15 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(158): Illuminate\Database\Eloquent\Builder->eagerLoadRelations(Array)
#16 /var/www/html/paperwork/frontend/app/lib/Paperwork/Db/PaperworkDbNoteObject.php(54): Illuminate\Database\Eloquent\Builder->get()
#17 /var/www/html/paperwork/frontend/app/controllers/api/v1/ApiNotesController.php(123): Paperwork\Db\PaperworkDbNoteObject->get(Array)
#18 [internal function]: ApiNotesController->index('3')
#19 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#20 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('index', Array)
#21 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(ApiNotesController), Object(Illuminate\Routing\Route), 'index')
#22 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ApiNotesControl...', 'index')
#23 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('3')
#24 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#25 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#26 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#29 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#30 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#31 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#32 /var/www/html/paperwork/frontend/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#33 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#34 /var/www/html/paperwork/frontend/public/index.php(49): Illuminate\Foundation\Application->run()
#35 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'versions.user_id' in 'field list' (SQL: select `versions`.`id`, `versions`.`title`, `versions`.`content_preview`, `versions`.`content`, `versions`.`user_id` from `versions` where `versions`.`deleted_at` is null and `versions`.`id` in (51, 13, 36))' in /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('select `version...', Array, Object(Closure))
#1 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\Database\Connection->run('select `version...', Array, Object(Closure))
#2 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1412): Illuminate\Database\Connection->select('select `version...', Array)
#3 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1397): Illuminate\Database\Query\Builder->runSelect()
#4 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1384): Illuminate\Database\Query\Builder->getFresh(Array)
#5 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(411): Illuminate\Database\Query\Builder->get(Array)
#6 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(151): Illuminate\Database\Eloquent\Builder->getModels(Array)
#7 [internal function]: Illuminate\Database\Eloquent\Builder->get()
#8 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(281): call_user_func_array(Array, Array)
#9 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(103): Illuminate\Database\Eloquent\Relations\Relation->__call('get', Array)
#10 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(103): Illuminate\Database\Eloquent\Relations\BelongsTo->get()
#11 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(476): Illuminate\Database\Eloquent\Relations\Relation->getEager()
#12 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(445): Illuminate\Database\Eloquent\Builder->loadRelation(Array, 'version', Object(Closure))
#13 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(158): Illuminate\Database\Eloquent\Builder->eagerLoadRelations(Array)
#14 /var/www/html/paperwork/frontend/app/lib/Paperwork/Db/PaperworkDbNoteObject.php(54): Illuminate\Database\Eloquent\Builder->get()
#15 /var/www/html/paperwork/frontend/app/controllers/api/v1/ApiNotesController.php(123): Paperwork\Db\PaperworkDbNoteObject->get(Array)
#16 [internal function]: ApiNotesController->index('3')
#17 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#18 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('index', Array)
#19 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(ApiNotesController), Object(Illuminate\Routing\Route), 'index')
#20 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ApiNotesControl...', 'index')
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('3')
#22 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#23 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#24 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#27 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#30 /var/www/html/paperwork/frontend/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#31 /var/www/html/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#32 /var/www/html/paperwork/frontend/public/index.php(49): Illuminate\Foundation\Application->run()
#33 {main} [] []
````

**Comment by Baldrs** [comment]
You need to run migrations first. They could fail, the you may end up patching the database manually. Please remember that paperwork is still very unstable software.

**Comment by doc-jay** [comment]
thanks -

I just ran 'php artisan migrate' and you guessed it, it failed.

````
  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'paperworkdb.tag_user' (SQL: drop table `tag_user`)

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'paperworkdb.tag_user'
````

any pointers for me?

**Comment by Baldrs** [comment]
I've added fix for that to the develop branch. Can you please try it and report any new errors?

**Comment by doc-jay** [comment]
absolutely, thank you very much!  One quick question which i'm sure will be an easy one for you, not a heavy git user, but when I run 'php artisan paperwork:update' it comes back with:

From https://github.com/twostairs/paperwork
   19c6616..defbe65  develop    -> origin/develop
error: Your local changes to the following files would be overwritten by merge:
        frontend/app/database/migrations/2014_07_22_194050_initialize.php
        frontend/app/database/migrations/2014_07_24_103915_create_password_reminders_table.php
        frontend/app/database/migrations/2014_10_08_203732_add_visibility_to_tags_table.php
        frontend/app/database/migrations/2015_01_21_034728_add_admin_to_users.php
        frontend/app/database/migrations/2015_05_05_094021_modify_tag_user_relation.php
        frontend/app/database/migrations/2015_05_22_220540_add_version_user_relation.php
        frontend/app/database/migrations/2015_06_15_224221_add_tag_parent.php
Please, commit your changes or stash them before you can merge.
Aborting
Updating 19c6616..defbe65
Command returned Updating 19c6616..defbe65

how do just tell it to 'overwrite' them?

**Comment by Baldrs** [comment]
Issue following commands: 

    git stash 
    php artisan paperwork:update
    git stash apply

Be aware that the last step can bring some problems regarding difference between actual files and stashed ones, so it could be easier just to reconfgure paperwork from scratch.

**Comment by doc-jay** [comment]
lol, your absolutely right!

**Comment by Baldrs** [comment]
I assume your issue is resolved. Please get in touch with me in gitter if you have some additional problems. Have a nice time of day :-)
