### ISSUE TITLE
docker version doesnt work

### ISSUE THREAD

**Issue by ShashankaNataraj** [twostairs/paperwork#833]
Followed the wiki and ran:

`docker-compose up` but Im getting the below error:

    bootstrap-css-only#3.3.7 app/js/bower_components/bootstrap-css-only
    
    rangy#1.3.0 app/js/bower_components/rangy
    
    bootstrap3-ie10-viewport-bug-workaround#1.0.0 app/js/bower_components/bootstrap3-ie10-viewport-bug-workaround
    └── bootstrap#3.3.7
    
    font-awesome#4.7.0 app/js/bower_components/font-awesome
    
    bootstrap#3.3.7 app/js/bower_components/bootstrap
    └── jquery#1.11.3
    
    module.js:340
        throw err;
        ^
    Error: Cannot find module 'http-parser-js'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/app/node_modules/gulp-livereload/node_modules/mini-lr/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/http_parser.js:3:22)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
    ERROR: Service 'web' failed to build: The command '/bin/sh -c find ./app/storage -type d -print0 | xargs -0 chmod 0755 &&     find ./app/storage -type f -print0 | xargs -0 chmod 0644 &&     composer install && npm update && npm install &&     npm install -g gulp bower && bower --allow-root install && gulp &&     chown -R www-data:www-data /app && chmod +x /app/docker-runner.sh' returned a non-zero code: 8

**Comment by jsEveryDay** [comment]
Don't know much about docker but I don't see how docker is needed here....
run `npm install http-parser-js`
then try again

if error then report your error and Node version.
Most http modules have been depreciated since the native http is now very stable and covers all aspects. Even express is slowly rolling out. Native http is so much more efficient.

**Comment by xenithorb** [comment]
Got this one myself:

```
font-awesome#4.7.0 app/js/bower_components/font-awesome
module.js:471
    throw err;
    ^

Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
ERROR: Service 'web' failed to build: The command '/bin/sh -c find ./app/storage -type d -print0 | xargs -0 chmod 0755 &&     find ./app/storage -type f -print0 | xargs -0 chmod 0644 &&     composer install && npm update && npm install &&     npm install -g gulp bower && bower --allow-root install && gulp &&     chown -R $UID:$GID /app && chmod +x /usr/local/bin/docker-runner.sh' returned a non-zero code: 1
```

**Comment by Liongold** [comment]
A pull request #854 has been opened to fix the jshint warning.

**Comment by Liongold** [comment]
The pull request mentioned has been merged to both the 'develop' and 'master' branches. Thus, this issue will be closed. If you encounter any issues with Paperwork, feel free to open a new issue. Thanks for using Paperwork.
